import React, { useState, useEffect } from "react";
import ViewPortCheck from "./ViewPortCheck";

function ScrollViewport() {
  return (
    <div>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
    <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>
      <h1>Some thing</h1>

    </div>
  );
}

export default ScrollViewport;
